name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run test 1 
        run: echo -n "apple" | python app/main.py -E "a"

      - name: Run test 2 
        run: echo -n "apple123" | python app/main.py -E "\d"

      - name: Run test 3 
        run: echo -n "alpha-num3ric" | python app/main.py -E "\w"

      - name: Run test 4 
        run: echo -n "apple" | python app/main.py -E "[abc]"

      - name: Run test 5 
        run: |
         echo -n "apple" | python app/main.py -E "[^abc]"
         echo -n "apple" | python app/main.py -E "[^bcd]"

      - name: Run test 6 
        run: |
         echo -n "1 apple" | python app/main.py -E "\d apple"
 
      - name: Run test 7 
        run: |
         echo -n "log" | python app/main.py -E "^log"
